server:
  port: 5001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eshop
    username: root
    password: root
  application:
    name: productServer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


feign:
  sentinel:
    enabled: true